import { NextPage } from "next";
import Footer from "./footer";
import Header from "./header";
import styles from '../styles/Home.module.css'
import Head from "next/head";

interface LayoutProps {
    children: React.ReactNode
}

const Layout: NextPage<LayoutProps> = ({children}) => {
    return (
        <div className="content">
            <Head>
                <title>Next Burger App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={styles.main}>
                <Header />
                {children}
                <Footer />
            </main>
        </div>
    )
}

export default Layout